<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TaskFlow Export</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 12px;
            color: #334155;
            line-height: 1.5;
        }
        .header {
            border-bottom: 2px solid #4F46E5;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header table {
            width: 100%;
        }
        .title {
            font-size: 20px;
            font-weight: bold;
            color: #4F46E5;
        }
        .date {
            text-align: right;
            color: #64748b;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .table th {
            background-color: #f1f5f9;
            color: #1e293b;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 10px;
            border: 1px solid #cbd5e1;
            padding: 8px;
            text-align: left;
        }
        .table td {
            border: 1px solid #cbd5e1;
            padding: 8px;
            vertical-align: top;
        }
        .priority-high {
            color: #ef4444;
            font-weight: bold;
        }
        .priority-medium {
            color: #f59e0b;
            font-weight: bold;
        }
        .priority-low {
            color: #06b6d4;
            font-weight: bold;
        }
        .status-completed {
            text-decoration: line-through;
            color: #94a3b8;
        }
        .footer {
            margin-top: 30px;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
            text-align: center;
            font-size: 10px;
            color: #64748b;
        }
    </style>
</head>
<body>

<div class="header">
    <table>
        <tr>
            <td class="title">TaskFlow Export</td>
            <td class="date">
                User: {{ $user->name }}<br>
                Date: {{ now()->format('d M Y, h:i A') }}
            </td>
        </tr>
    </table>
</div>

<h3>Exported Tasks</h3>

<table class="table">
    <thead>
        <tr>
            <th style="width: 5%;">#</th>
            <th style="width: 35%;">Task Details</th>
            <th style="width: 15%;">Category</th>
            <th style="width: 10%;">Priority</th>
            <th style="width: 10%;">Status</th>
            <th style="width: 15%;">Due Date</th>
            <th style="width: 10%;">Est. Time</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($tasks as $index => $task)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>
                    <span class="fw-bold {{ $task->status === 'Completed' ? 'status-completed' : '' }}" style="font-weight: bold;">
                        {{ $task->title }}
                    </span>
                    @if($task->description)
                        <div style="font-size: 10px; color: #64748b; margin-top: 4px;">
                            {{ $task->description }}
                        </div>
                    @endif
                </td>
                <td>
                    {{ $task->category?->name ?? 'N/A' }}
                </td>
                <td>
                    <span class="priority-{{ strtolower($task->priority) }}">
                        {{ $task->priority }}
                    </span>
                </td>
                <td>
                    {{ $task->status }}
                </td>
                <td>
                    @if ($task->due_date)
                        {{ $task->due_date->format('d M Y') }}
                        @if ($task->due_time)
                            <div style="font-size: 10px; color: #64748b;">
                                {{ Carbon\Carbon::parse($task->due_time)->format('g:i A') }}
                            </div>
                        @endif
                    @else
                        N/A
                    @endif
                </td>
                <td>
                    {{ $task->estimated_minutes ? $task->estimated_minutes . ' min' : '—' }}
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="7" style="text-align: center; padding: 20px; color: #64748b;">
                    No tasks found.
                </td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Generated by TaskFlow Productivity and Daily Planning System.
</div>

</body>
</html>
